
import { Portal } from '@/types/portals';

export const portals: Portal[] = [
  {
    id: 'cooperative-purchasing',
    name: 'Cooperative Purchasing',
    nameAr: 'الشراء التعاوني',
    description: 'Group purchasing platform for better deals',
    descriptionAr: 'منصة الشراء الجماعي للحصول على صفقات أفضل',
    icon: '🛒',
    color: 'border-l-blue-500',
    route: '/portal/cooperative-purchasing',
    isActive: true,
    requiresKyc: true,
    requiresPoints: true,
    minimumPoints: 100,
    features: [
      {
        id: 'group-formation',
        name: 'Group Formation',
        nameAr: 'تكوين المجموعات',
        description: 'Create and manage purchasing groups',
        descriptionAr: 'إنشاء وإدارة مجموعات الشراء',
        isEnabled: true
      }
    ]
  },
  {
    id: 'cooperative-marketing',
    name: 'Cooperative Marketing',
    nameAr: 'التسويق التعاوني',
    description: 'Collaborative marketing campaigns',
    descriptionAr: 'حملات التسويق التعاونية',
    icon: '📊',
    color: 'border-l-green-500',
    route: '/portal/cooperative-marketing',
    isActive: true,
    requiresKyc: false,
    requiresPoints: true,
    minimumPoints: 50,
    features: []
  },
  {
    id: 'company-formation',
    name: 'Company Formation',
    nameAr: 'تأسيس الشركات',
    description: 'Business incorporation services',
    descriptionAr: 'خدمات تأسيس الأعمال',
    icon: '🏢',
    color: 'border-l-purple-500',
    route: '/portal/company-formation',
    isActive: true,
    requiresKyc: true,
    requiresPoints: true,
    minimumPoints: 500,
    features: []
  },
  {
    id: 'investment-groups',
    name: 'Investment Groups',
    nameAr: 'مجموعات الاستثمار',
    description: 'Collaborative investment opportunities',
    descriptionAr: 'فرص الاستثمار التعاونية',
    icon: '💰',
    color: 'border-l-yellow-500',
    route: '/portal/investment-groups',
    isActive: true,
    requiresKyc: true,
    requiresPoints: true,
    minimumPoints: 1000,
    features: []
  },
  {
    id: 'suppliers',
    name: 'Suppliers',
    nameAr: 'الموردين',
    description: 'Supplier network and management',
    descriptionAr: 'شبكة وإدارة الموردين',
    icon: '🏭',
    color: 'border-l-red-500',
    route: '/portal/suppliers',
    isActive: true,
    requiresKyc: true,
    requiresPoints: false,
    features: []
  },
  {
    id: 'freelancers',
    name: 'Freelancers',
    nameAr: 'المستقلين',
    description: 'Freelance services marketplace',
    descriptionAr: 'سوق خدمات العمل الحر',
    icon: '💼',
    color: 'border-l-indigo-500',
    route: '/portal/freelancers',
    isActive: true,
    requiresKyc: false,
    requiresPoints: true,
    minimumPoints: 25,
    features: []
  },
  {
    id: 'freelancer-groups',
    name: 'Freelancer Groups',
    nameAr: 'مجموعات المستقلين',
    description: 'Collaborative freelancer teams',
    descriptionAr: 'فرق المستقلين التعاونية',
    icon: '👥',
    color: 'border-l-pink-500',
    route: '/portal/freelancer-groups',
    isActive: true,
    requiresKyc: false,
    requiresPoints: true,
    minimumPoints: 100,
    features: []
  },
  {
    id: 'service-providers',
    name: 'Service Providers',
    nameAr: 'مقدمي الخدمات',
    description: 'Professional service providers',
    descriptionAr: 'مقدمي الخدمات المهنية',
    icon: '🔧',
    color: 'border-l-teal-500',
    route: '/portal/service-providers',
    isActive: true,
    requiresKyc: true,
    requiresPoints: false,
    features: []
  },
  {
    id: 'product-listings',
    name: 'Product Listings',
    nameAr: 'قوائم المنتجات',
    description: 'Product catalog and listings',
    descriptionAr: 'كتالوج وقوائم المنتجات',
    icon: '📦',
    color: 'border-l-orange-500',
    route: '/portal/product-listings',
    isActive: true,
    requiresKyc: false,
    requiresPoints: false,
    features: []
  },
  {
    id: 'arbitration-documentation',
    name: 'Arbitration & Documentation',
    nameAr: 'التحكيم والتوثيق',
    description: 'Legal arbitration and document services',
    descriptionAr: 'خدمات التحكيم القانوني والتوثيق',
    icon: '⚖️',
    color: 'border-l-gray-500',
    route: '/portal/arbitration-documentation',
    isActive: true,
    requiresKyc: true,
    requiresPoints: true,
    minimumPoints: 200,
    features: []
  },
  {
    id: 'arbitration-requests',
    name: 'Arbitration Requests',
    nameAr: 'طلبات التحكيم',
    description: 'Submit and manage arbitration requests',
    descriptionAr: 'تقديم وإدارة طلبات التحكيم',
    icon: '📋',
    color: 'border-l-cyan-500',
    route: '/portal/arbitration-requests',
    isActive: true,
    requiresKyc: true,
    requiresPoints: true,
    minimumPoints: 150,
    features: []
  },
  {
    id: 'smart-negotiation',
    name: 'Smart Negotiation Solutions',
    nameAr: 'حلول التفاوض الذكية',
    description: 'AI-powered negotiation platform',
    descriptionAr: 'منصة التفاوض المدعومة بالذكاء الاصطناعي',
    icon: '🤝',
    color: 'border-l-emerald-500',
    route: '/portal/smart-negotiation',
    isActive: true,
    requiresKyc: false,
    requiresPoints: true,
    minimumPoints: 75,
    features: []
  }
];
